### ISSUE TITLE
Error on checking Bastion Hosts

### ISSUE THREAD

**Issue by tldtech** [thgossler/AzSaveMoney#2]
When the script tries to check bastion hosts, it returns the following:
**_Exception type: ErrorResponseException, Message: Microsoft.Azure.Management.Monitor.Models.ErrorResponseException: Operation returned an invalid status code 'BadRequest'
   at Microsoft.Azure.Management.Monitor.MetricsOperations.ListWithHttpMessagesAsync(String resourceUri, ODataQuery`1 odataQuery, String timespan, Nullable`1 interval, String metricnames, String aggregation, Nullable`1 top, String orderby, Nullable`1 resultType, String metricnamespace, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Monitor.MetricsOperationsExtensions.ListAsync(IMetricsOperations operations, String resourceUri, ODataQuery`1 odataQuery, String timespan, Nullable`1 interval, String metricnames, String aggregation, Nullable`1 top, String orderby, Nullable`1 resultType, String metricnamespace, CancellationToken cancellationToken)
   at Microsoft.Azure.Commands.Insights.Metrics.GetAzureRmMetricCommand.ProcessRecordInternal()
   at Microsoft.Azure.Commands.Insights.MonitorCmdletBase.ExecuteCmdlet(), Code: Null, Status code:Null, Reason phrase: Null_**

Specifically, this function:
```
function Test-ResourceActionHook-microsoft-network-bastionhosts($Resource) {
    Write-Host "Testing Bastion NOW for resource $Resource."
    PAUSE
    $periodInDays = 35
    $totalNumberOfSessions = Get-Metric -ResourceId $Resource.id -MetricName 'sessions' -AggregationType Total -PeriodInDays $periodInDays
    if ($null -ne $totalNumberOfSessions -and $totalNumberOfSessions.Sum -lt 1) {
        return [ResourceAction]::markForDeletion, "The Bastion host had no sessions for $periodInDays days."
    }
    return [ResourceAction]::none, ""
}
```

More specifically, this line in the fuction:
`Get-Metric -ResourceId $Resource.id -MetricName 'sessions' -AggregationType Total -PeriodInDays $periodInDays`

I see underneath that the function is calling _**Get-AzMetric**_. If I grab a bastion and throw it into the "$Resource" variable and try it manually, it works. Like so:
`Get-AzMetric -ResourceId $Resource.Id -MetricName 'sessions' -AggregationType 'Total' -StartTime (Get-Date -AsUTC).AddDays(-$PeriodInDays) -EndTime (Get-Date -AsUTC) -TimeGrain ([timespan]::FromHours($TimeGrainInHours).ToString()) -ErrorAction Continue`

This returns proper output:
_Id              : REDATCTED
Name       :
                LocalizedValue : Session Coun
                Value          : sessions

Type       : Microsoft.Insights/metrics
Unit       : Count
Data       : {Microsoft.Azure.Commands.Insights.OutputClasses.PSMetricValue, Microsoft.Azure.Commands.Insights.OutputClasses.PSMetricValue, Microsoft.Azure.Commands.Insights.OutputClasses.PSMetricValue,
             Microsoft.Azure.Commands.Insights.OutputClasses.PSMetricValue…}
Timeseries : {Microsoft.Azure.Management.Monitor.Models.TimeSeriesElement}_

The issue is related to the "TimeGrainInHours" switch. If I set it to "0" the function works. However set to "24" throws the above error.

If I run a "-verbose -debug" on the Get-AzMetric command I see this in the results from the API:
**_Body:
{
  "code": "BadRequest",
  "message": "Commonly allowed time grains: 00:05:00,00:15:00 between metrics: sessions, can not support requested time grain: 1.00:00:00 please adjust your interval parameter to use one of the common grains, TraceId: {77870d4c-05ba-4a5d-983a-6c343f67544b}"
}_**

This all comes down to **_"-AggregationType 'Total'"_** and  **_"-MetricName 'Sessions'"_** being used with **_"-TimeGrain ([timespan]::FromHours($TimeGrainInHours).ToString())."_** Remove one or the other and it works.

**Comment by thgossler** [comment]
Thanks for reporting!

I don't see a reason why this should always happen. Did you try it again after a while with the script and can confirm that it is still happening? Sometimes a BadRequest is occurring when there is a temporary network or service outage.

**Comment by tldtech** [comment]
I tried many times but could never get it to work.
I ended up adding another function just for bastion hosts.

**Comment by thgossler** [comment]
I could reproduce the issue. It seems to be a bug in Get-AzMetric when using a TimeGrain argument. I have added a temporary workaround with commit [c796636](https://github.com/thgossler/AzSaveMoney/commit/c7966362a510ad345abf32760e99d6c0a08acd14).
