### ISSUE TITLE
Cannot bind parameter 'ForegroundColor'

### ISSUE THREAD

**Issue by BramMaerevoet** [thgossler/AzSaveMoney#3]
Hello, with the new script published in January I get the error on line 233 (Write-HostOrObjec Function):

Cannot bind parameter 'ForegroundColor' to the target. Exception setting "ForegroundColor": "Cannot convert null to type "System.ConsoleColor" due to enumeration values that are not valid. Specify one of the following enumeration
     | values and try again. The possible enumeration values are "Black,DarkBlue,DarkGreen,DarkCyan,DarkRed,DarkMagenta,DarkYellow,Gray,DarkGray,Blue,Green,Cyan,Red,Magenta,Yellow,White"."

I'm unable to resolve this issue... Anyone else have the same problem?

**Comment by thgossler** [comment]
@BramMaerevoet, please try again with the latest update and let me know if it works again for you. I found a bug which could have caused that error.

**Comment by BramMaerevoet** [comment]
@thgossler the color issue is fixed, thanks. But now I get 2 other errors:

1) Line 755, 1013, 1014, 1134 and 1144 "A parameter cannot be found that matches parameter name 'NoNewline'." I removed the parameter at every line, this works and that doesn't seem to break the code.

2) Line 1145 gives "Cannot bind argument to parameter 'Message' because it is an empty string."

**Comment by thgossler** [comment]
I have fixed this as well. You can try again with the latest changes.

**Comment by BramMaerevoet** [comment]
Issue is resolved. Thanks!
