### ISSUE TITLE
SubjectForDeletion = rejected not working

### ISSUE THREAD

**Issue by BramMaerevoet** [thgossler/AzSaveMoney#4]
Hello, it seems that when a resource is tagged as 'rejected', the script doesn't skip the resources and tags it again as supsected.

**Comment by thgossler** [comment]
I have reviewed the 'rejected' handling logic again comprehensively and found a bug. Thanks for your feedback!

Further, in the docs it is mentioned that after 6 months a rejected state is reset to suspected again to prevent that unused resources remain undetected infinitely. But that part was not implemented yet, a rejected state is never reset or overwritten at the moment.

The necessary changed are implemented now but need to undergo some testing yet. The new reset logic will be disabled by default and needs to be enabled explicitly if wanted. 

Expect a commit in the next days.
